Feature/GN-3787
lblod/frontend-gelinkt-notuleren-publicatie pull request #69
Opened 2022-11-08 15:21 UTC by usrtim

Currently the meeting overview page on publication platform is fetching all content linked to the meeting. I added the **Sparse fieldsets** to limit the amount of data we are fetching. In the first image is shown how It was before:

<img width="642" alt="Screenshot 2022-11-08 at 4 14 53 PM" src="https://user-images.githubusercontent.com/115715476/200603881-cf8ae7a3-e719-4bba-b908-319071347259.png">

and on second image below, It's the new data that we are fetching:

<img width="639" alt="Screenshot 2022-11-08 at 4 15 15 PM" src="https://user-images.githubusercontent.com/115715476/200604051-b95c5a86-c8bf-4730-b0bd-e8b9ce6f6425.png">

Please let me know, If I'm missing something.

2022-11-09 16:36 UTC, elpoelma requested changes
Good start, but I notice that for example the document contents of agendas and uittreksels are still fetched on the meeting overview page, which should not be necessary I think. I would also omit them using sparse fieldsets. 
![image](https://user-images.githubusercontent.com/24712836/200887608-e7504077-2167-4feb-b5fb-8e8673396112.png)

2022-11-09 17:17 UTC, abeforgit commented
> Good start, but I notice that for example the document contents of agendas and uittreksels are still fetched on the meeting overview page, which should not be necessary I think. I would also omit them using sparse fieldsets. ![image](https://user-images.githubusercontent.com/24712836/200887608-e7504077-2167-4feb-b5fb-8e8673396112.png)

Was looking into this exact thing, and while I was at playing with the fields param I got it working and it felt silly not to push

2022-11-09 17:21 UTC, abeforgit approved these changes

2022-11-14 09:50 UTC, elpoelma approved these changes

2022-11-14 09:51 UTC, merged